export const GAME_AREA_ID = "game-area"
export const GAME_AREA_SELECTOR = "#" + GAME_AREA_ID
export const SCORE_ID = "score"
export const SCORE_SELECTOR = "#" + SCORE_ID
export const PAUSE_BUTTON_ID = "pause-button"
export const PAUSE_BUTTON_SELECTOR = "#" + PAUSE_BUTTON_ID
export const HIGHSCORE_ID = "highscore"
export const HIGHSCORE_SELECTOR = "#" + HIGHSCORE_ID
export const SPEED_SLIDER_ID = "speed-selector"
export const SPEED_SLIDER_SELECTOR = "#" + SPEED_SLIDER_ID
export const SPEED_DISPLAY_ID = "speed-display"
export const SPEED_DISPLAY_SELECTOR = "#" + SPEED_DISPLAY_ID
export const SCOREBOARD_ID = "scoreboard"
export const SCOREBOARD_SELECTOR = "#" + SCOREBOARD_ID
export const NAME_INPUT_ID = "your-name"
export const NAME_INPUT_SELECTOR = "#" + NAME_INPUT_ID

export const LOCALSTORAGE_PERSONAL_HIGHSCORE_ID = "personal-highscore"
export const LOCALSTORAGE_NAME_ID = "your-name"
